# playbook.yml
- name: staging playbook
  hosts: staging-region
  become: yes
  tasks:
    - name: Test connectivity
      ping:

    - name: Install Apache
      apt:
        name: apache2
        state: present
        update_cache: yes

    - name: Ensure Apache is running
      service:
        name: apache2
        state: started
