 - name: Install and configure web servers
   hosts: staging
   become: yes

   tasks:
     - name: Ensure Apache is installed
       apt:
         name: apache2
         state: present

     - name: start and enable apache2
       systemd:
         name: apache2
         state: started
         enabled: yes

     - name: copy the website content
       copy:
         src: ./index.html
         dest: /var/www/html/